import type { GraderDef } from "../grade/types";

export const graders: Record<string, () => Promise<GraderDef>> = {
  // fill / data
  "fill-sum-numbers": () => import("./data/sum-numbers").then((m) => m.default),
  "fill-filter-evens": () => import("./data/filter-evens").then((m) => m.default),
  "fill-map-double": () => import("./data/map-double").then((m) => m.default),
  "fill-sum-sales": () => import("./data/sum-sales").then((m) => m.default),
  "fill-find-product": () => import("./data/find-product").then((m) => m.default),
  "fill-some-positive": () => import("./data/some-positive").then((m) => m.default),
  "fill-sort-names": () => import("./data/sort-names").then((m) => m.default),
  "fill-entries-tax": () => import("./data/entries-tax").then((m) => m.default),
  "fill-split-csv": () => import("./data/split-csv").then((m) => m.default),
  "fill-replace-template": () => import("./data/replace-template").then((m) => m.default),
  // fill / gas
  "fill-gas-sum-column": () => import("./gas/sum-column").then((m) => m.default),
  "fill-gas-conditional-sum": () => import("./gas/conditional-sum").then((m) => m.default),
  // fill / email
  "fill-email-weekly": () => import("./email/weekly-report").then((m) => m.default),
  "fill-email-personalized": () => import("./email/personalized-send").then((m) => m.default),
  // fill / chrome
  "fill-chrome-fill-form": () => import("./chrome/fill-form").then((m) => m.default),
  "fill-chrome-get-text": () => import("./chrome/get-text").then((m) => m.default),
  // read
  "read-star-count": () => import("./read/star-count").then((m) => m.default),
  "read-greeting": () => import("./read/greeting").then((m) => m.default),
  "read-progress": () => import("./read/progress").then((m) => m.default),
  "read-color-box": () => import("./read/color-box").then((m) => m.default),
  "read-bool-light": () => import("./read/bool-light").then((m) => m.default),
  // write
  "write-average": () => import("./data/average").then((m) => m.default),
  "write-max-value": () => import("./data/max-value").then((m) => m.default),
  "write-unique": () => import("./data/unique").then((m) => m.default),
  "write-group-sum": () => import("./data/group-sum").then((m) => m.default),
  "write-gas-rows-to-obj": () => import("./gas/rows-to-obj").then((m) => m.default),
  "write-email-make-subject": () => import("./email/make-subject").then((m) => m.default),
  // bash / jq
  "bash-jq-pick-names": () => import("./jq/pick-names").then((m) => m.default),
  "bash-jq-length": () => import("./jq/length").then((m) => m.default),
  "bash-jq-first-user-name": () => import("./jq/first-user-name").then((m) => m.default),
  "bash-jq-sum-ages": () => import("./jq/sum-ages").then((m) => m.default),
  "bash-jq-filter-adult": () => import("./jq/filter-adult").then((m) => m.default),
  "bash-jq-map-double": () => import("./jq/map-double").then((m) => m.default),
  "bash-jq-keys": () => import("./jq/keys").then((m) => m.default),
  "bash-jq-has-key": () => import("./jq/has-key").then((m) => m.default),
  "bash-jq-sort-by-age": () => import("./jq/sort-by-age").then((m) => m.default),
  "bash-jq-max-by-age": () => import("./jq/max-by-age").then((m) => m.default),
  "bash-jq-unique-values": () => import("./jq/unique-values").then((m) => m.default),
  "bash-jq-group-count": () => import("./jq/group-count").then((m) => m.default),
  "bash-jq-to-entries": () => import("./jq/to-entries").then((m) => m.default),
  "bash-jq-string-interp": () => import("./jq/string-interp").then((m) => m.default),
  "bash-jq-if-then-else": () => import("./jq/if-then-else").then((m) => m.default),
  "bash-jq-select-and": () => import("./jq/select-and").then((m) => m.default),
  "bash-jq-nested-path": () => import("./jq/nested-path").then((m) => m.default),
  "bash-jq-array-construct": () => import("./jq/array-construct").then((m) => m.default),
  "bash-jq-alt-operator": () => import("./jq/alt-operator").then((m) => m.default),
  "bash-jq-join": () => import("./jq/join").then((m) => m.default),
  // bash / シェル（本物の bash / WASM）
  "bash-sh-greet-loop": () => import("./sh/greet-loop").then((m) => m.default),
  "bash-sh-if-even-odd": () => import("./sh/if-even-odd").then((m) => m.default),
  "bash-sh-sum-two": () => import("./sh/sum-two").then((m) => m.default),
  "bash-sh-count-down": () => import("./sh/count-down").then((m) => m.default),
  "bash-sh-string-upper": () => import("./sh/string-upper").then((m) => m.default),
  "bash-sh-string-length": () => import("./sh/string-length").then((m) => m.default),
  "bash-sh-array-sum": () => import("./sh/array-sum").then((m) => m.default),
  "bash-sh-max-of-three": () => import("./sh/max-of-three").then((m) => m.default),
  "bash-sh-fizzbuzz": () => import("./sh/fizzbuzz").then((m) => m.default),
  "bash-sh-reverse-string": () => import("./sh/reverse-string").then((m) => m.default),
  "bash-sh-function-greet": () => import("./sh/function-greet").then((m) => m.default),
  "bash-sh-while-read-lines": () => import("./sh/while-read-lines").then((m) => m.default),
  "bash-sh-case-day": () => import("./sh/case-day").then((m) => m.default),
  "bash-sh-default-value": () => import("./sh/default-value").then((m) => m.default),
  "bash-sh-substring": () => import("./sh/substring").then((m) => m.default),
  "bash-sh-string-replace": () => import("./sh/string-replace").then((m) => m.default),
  "bash-sh-positional-params": () => import("./sh/positional-params").then((m) => m.default),
  "bash-sh-nested-loop": () => import("./sh/nested-loop").then((m) => m.default),
  "bash-sh-array-filter": () => import("./sh/array-filter").then((m) => m.default),
  "bash-sh-here-string": () => import("./sh/here-string").then((m) => m.default),
};
